# Generated by Django 4.1.5 on 2023-12-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='texto',
            field=models.TextField(default=''),
        ),
    ]
